name: Automatically Generate Documentation

on: [push, pull_request_target]

jobs:
  generate-documentation:
    strategy:
      fail-fast: false
      matrix:
        version:
          - nightly
    name: Generate Markdown Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Plenary
        uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: Install Treesitter
        uses: actions/checkout@v2
        with:
          repository: nvim-treesitter/nvim-treesitter
          path: nvim-treesitter
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: ${{ matrix.version }}

      - name: Run Documentation Generator
        run: |
          make ci-doc
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ ! -z $(git status -s) ]]; then
            git add wiki/
            git commit -m "chore: autogenerate wiki pages"
          fi

      - name: Push Documentation to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: .

      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: "nvim-neorg/neorg.wiki"
          path: neorg-wiki

      - name: Move Wiki Files
        run: |
          mv ./neorg/wiki/**.md ./neorg-wiki -f

      - name: Commit Wiki Changes
        run: |
          cd neorg-wiki
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: autoupdate github wiki"

      - name: Push Wiki to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: "nvim-neorg/neorg.wiki"
          branch: master
          force: true
          directory: ./neorg-wiki
