name: Formatting

on: [push, pull_request_target]

jobs:
  format-with-stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://sh.rustup.rs -sSf | sh
      - run: cargo install stylua --features lua52
      - run: stylua -v --verify .
