name: lua_ls-typecheck
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout neovim for type annotations
        uses: actions/checkout@v3
        with:
          repository: "neovim/neovim"
          path: "deps/neovim"

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.2.1
        with:
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
